Repository dsc-sookmyung/2022-Answer-SolutionChallenge, pull requests merged in 2022-03, with the labels that each got.

#22 feat: Notice OCR API
  spring/notinote/.gitignore
  spring/notinote/build.gradle
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/repository/NoticeRepository.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/ImageRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end

#27 feat: Notice Translate API
  spring/notinote/build.gradle
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end

#15 [#5] feat: join, login api
  .idea/.gitignore
  .idea/2022-Answer-SolutionChallenge.iml
  .idea/dbnavigator.xml
  .idea/modules.xml
  .idea/vcs.xml
  spring/notinote/build.gradle
  spring/notinote/src/main/java/com/answer/notinote/Config/properties/AppProperties.java
  spring/notinote/src/main/java/com/answer/notinote/Config/properties/CorsProperties.java
  spring/notinote/src/main/java/com/answer/notinote/Config/security/JwtConfig.java
  spring/notinote/src/main/java/com/answer/notinote/Config/security/WebSecurityConfig.java
  spring/notinote/src/main/java/com/answer/notinote/NotinoteApplication.java
  spring/notinote/src/main/java/com/answer/notinote/User/controller/UserController.java
  spring/notinote/src/main/java/com/answer/notinote/User/domain/entity/Timestamped.java
  spring/notinote/src/main/java/com/answer/notinote/User/domain/entity/User.java
  spring/notinote/src/main/java/com/answer/notinote/User/domain/repository/UserRepository.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/JoinRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/LoginResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/TokenResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/UserRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/service/UserService.java
  spring/notinote/src/main/java/com/answer/notinote/User/util/ErrorMessage.java
  spring/notinote/src/main/java/com/answer/notinote/User/util/advice/TokenControllerAdvice.java
  spring/notinote/src/main/java/com/answer/notinote/User/util/exception/TokenRefreshException.java
  spring/notinote/src/main/java/com/answer/notinote/auth/data/ProviderType.java
  spring/notinote/src/main/java/com/answer/notinote/auth/data/RoleType.java
  spring/notinote/src/main/java/com/answer/notinote/auth/data/dto/UserRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/auth/data/dto/UserSocialResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/auth/filter/JwtAuthenticationFilter.java
  spring/notinote/src/main/java/com/answer/notinote/auth/filter/OAuth2AccessTokenAuthenticationFilter.java
  spring/notinote/src/main/java/com/answer/notinote/auth/handler/OAuth2LoginFailureHandler.java
  spring/notinote/src/main/java/com/answer/notinote/auth/handler/OAuth2LoginSuccessHandler.java
  spring/notinote/src/main/java/com/answer/notinote/auth/repository/RefreshTokenRepository.java
  spring/notinote/src/main/java/com/answer/notinote/auth/service/CustomUserDetailsService.java
  spring/notinote/src/main/java/com/answer/notinote/auth/service/LoadUserService.java
  spring/notinote/src/main/java/com/answer/notinote/auth/service/RefreshTokenService.java
  spring/notinote/src/main/java/com/answer/notinote/auth/strategy/GoogleLoadStrategy.java
  spring/notinote/src/main/java/com/answer/notinote/auth/strategy/ProviderLoadStrategy.java
  spring/notinote/src/main/java/com/answer/notinote/auth/token/AccessTokenAuthenticationProvider.java
  spring/notinote/src/main/java/com/answer/notinote/auth/token/AccessTokenProviderTypeToken.java
  spring/notinote/src/main/java/com/answer/notinote/auth/token/JwtToken.java
  spring/notinote/src/main/java/com/answer/notinote/auth/token/JwtTokenProvider.java
  spring/notinote/src/main/java/com/answer/notinote/auth/token/RefreshToken.java
  spring/notinote/src/main/java/com/answer/notinote/auth/userdetails/CustomUserDetails.java
  spring/notinote/src/main/resources/static/index.html
Labels: enhancement, 🌱back-end

#34 feat: refreshToken -> keep logged in
  spring/notinote/src/main/java/com/answer/notinote/Auth/filter/JwtAuthenticationFilter.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/repository/RefreshTokenRepository.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/service/RefreshTokenService.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/token/JwtToken.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/token/RefreshToken.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/token/provider/JwtTokenProvider.java
  spring/notinote/src/main/java/com/answer/notinote/Exception/ErrorCode.java
  spring/notinote/src/main/java/com/answer/notinote/User/controller/UserController.java
  spring/notinote/src/main/java/com/answer/notinote/User/domain/repository/UserRepository.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/LoginResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/service/UserService.java
Labels: 🌱back-end

#36 [#35] Search by date & Application introduction screen
  react-native/App.tsx
  react-native/app.json
  react-native/assets/images/button-background.png
  react-native/assets/images/family.png
  react-native/assets/images/image-upload.png
  react-native/package.json
  react-native/screens/HomeScreen.tsx
  react-native/screens/IntroductionScreen.tsx
  react-native/screens/LoginScreen.tsx
  react-native/screens/SearchResultScreen.tsx
  react-native/screens/SearchScreen.tsx
  react-native/types.ts
  react-native/yarn.lock
Labels: 🖌️front-end

#37 [#11] Feat: Implement modals
  react-native/components/BottomDrawer.tsx
  react-native/screens/TranslateScreen.tsx
  react-native/types.ts
Labels: 🖌️front-end

#29 feat: Cloud Natural Language
  spring/notinote/build.gradle
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end

#43 refactor: Connect Notice with User
  spring/notinote/build.gradle
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/ImageRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeSaveDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeTitleListDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end

#46 add cid, profileImage in response
  spring/notinote/src/main/java/com/answer/notinote/Auth/data/dto/UserAuthRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/data/dto/UserSocialResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/filter/OAuth2AccessTokenAuthenticationFilter.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/handler/OAuth2LoginFailureHandler.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/handler/OAuth2LoginSuccessHandler.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/service/LoadUserService.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/service/OAuthService.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/service/RefreshTokenService.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/strategy/GoogleLoadStrategy.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/strategy/ProviderLoadStrategy.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/token/AccessTokenProviderTypeToken.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/token/provider/AccessTokenAuthenticationProvider.java
  spring/notinote/src/main/java/com/answer/notinote/Auth/userdetails/GoogleUser.java
  spring/notinote/src/main/java/com/answer/notinote/Child/domain/Child.java
  spring/notinote/src/main/java/com/answer/notinote/Child/dto/ChildDto.java
  spring/notinote/src/main/java/com/answer/notinote/Config/security/WebSecurityConfig.java
  spring/notinote/src/main/java/com/answer/notinote/User/controller/UserController.java
  spring/notinote/src/main/java/com/answer/notinote/User/domain/entity/User.java
  spring/notinote/src/main/java/com/answer/notinote/User/dto/UserResponseDto.java
  spring/notinote/src/main/java/com/answer/notinote/User/service/UserService.java
Labels: 🌱back-end

#70 feat: extract event from notice
  spring/notinote/src/main/java/com/answer/notinote/Auth/service/CustomUserDetailsService.java
  spring/notinote/src/main/java/com/answer/notinote/Event/domain/Event.java
  spring/notinote/src/main/java/com/answer/notinote/Event/dto/EventRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeSentenceDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeTitleListDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end

#68 refactor: Search API
  spring/notinote/src/main/java/com/answer/notinote/Notice/domain/repository/NoticeRepository.java
  spring/notinote/src/main/java/com/answer/notinote/Search/controller/SearchController.java
  spring/notinote/src/main/java/com/answer/notinote/Search/dto/SearchDetailDto.java
  spring/notinote/src/main/java/com/answer/notinote/Search/dto/SearchListDto.java
  spring/notinote/src/main/java/com/answer/notinote/Search/dto/SearchResultDetailDto.java
  spring/notinote/src/main/java/com/answer/notinote/Search/service/SearchService.java
Labels: 🌱back-end

#71 feat: extract event's index from notice
  spring/notinote/src/main/java/com/answer/notinote/Event/domain/Event.java
  spring/notinote/src/main/java/com/answer/notinote/Event/dto/EventRequestDto.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeResponseBody.java
  spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java
Labels: 🌱back-end
